const fs = require('fs-extra');
const path = require('path');
const { exec } = require('child_process');

const templatesDir = path.join(__dirname, 'templates');

async function generateProject(projectName, database) {
  const targetDir = path.join(process.cwd(), projectName);
  const template = database === 'MongoDB' ? 'express-mongo-template' : 'express-sql-template';
  const templateDir = path.join(templatesDir, template);

  try {
    if (fs.existsSync(targetDir)) {
      console.error(`❌ Error: Directory '${projectName}' already exists! Choose a different name.`);
      process.exit(1);
    }

    await fs.copy(templateDir, targetDir);
    console.log(`\n✅ Successfully created ${projectName} with ${database} support!\n`);

    const envContent =
      database === 'MongoDB'
        ? `PORT=5000\nMONGO_URI=mongodb://localhost:27017/${projectName}\nJWT_SECRET=your_jwt_secret\nEMAIL_USER=your_email\nEMAIL_PASS=your_password`
        : `PORT=5000\nDB_HOST=localhost\nDB_USER=root\nDB_PASS=password\nDB_NAME=${projectName}\nJWT_SECRET=your_jwt_secret\nDB_DIALECT=your_database_dialect\nEMAIL_USER=your_email\nEMAIL_PASS=your_password`;

    await fs.writeFile(path.join(targetDir, '.env'), envContent);
    console.log('✅ .env file created successfully!');

    console.log('📦 Installing dependencies...');
    exec(`cd ${targetDir} && npm install`, (error, stdout, stderr) => {
      if (error) {
        console.error(`❌ Error installing dependencies: ${error.message}`);
        return;
      }
      console.log(stdout);
      console.error(stderr);
      console.log('✅ Installation complete! You can now run your project.');

      // Display the creator message
      console.log(`\n🎉 Project successfully generated by Express API Kit!\n`);
      console.log(`👨‍💻 Developed by: Muhammad Ahmad`);
      console.log(`📢 Support: If you like this tool, give it a star ⭐ on GitHub!\n`);
    });
  } catch (error) {
    console.error('❌ Error creating project:', error);
  }
}

module.exports = generateProject;
